### ISSUE TITLE
issue with y-axis and facer_nested

### ISSUE THREAD

**Issue by jfouret** [teunbrand/ggh4x#42] opened 2021-05-10 09:03 UTC
hi, 

I had a weird bug with your package (that I love).

with data having 6 column (x,y,cluster,batch,group,value) and the y value being different fro each "cluster".

When I run a code like below; the y ids from the first cluster are repeating themselves for each cluster's facet

I fixed different values to see point size I see differences thus only the y-axis is repeating and not all values.

```
ggplot(data,aes(x,y,size=value))+
facet_nest(cluster~batch+group,scales='free_y',space='free_y')+
geom_point()
```
lastly I did 

```
devtools::install_github('teunbrand/ggh4x',ref='v0.1.1')
```
And it fixed the issue.

I will try to come up with a more reproducible example later.

**Comment by teunbrand** [comment] 2021-06-23 21:15
I've tried the code below and couldn't reproduce the issue. As such, I'll be closing this issue. If somebody runs into similar problems and has code to reproduce the problem, I'll reopen the issue.

``` r
library(ggplot2)
library(ggh4x)

data <- expand.grid(cluster = 1:2,
                    batch = c("A", "B"),
                    group = 3:4)
data <- transform(
  data,
  x = rnorm(nrow(data)),
  y = rnorm(nrow(data)),
  value = rnorm(nrow(data))
)

ggplot(data, aes(x, y, size = value)) +
  geom_point() +
  facet_nested(cluster ~ batch + group,
               scales = "free_y", space = "free_y")
```

![](https://i.imgur.com/xJhQx6o.png)

<sup>Created on 2021-06-23 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Closed by teunbrand** 2021-06-23 21:15 UTC
