### ISSUE TITLE
geom_polygonraster - grey lines between pixels

### ISSUE THREAD

**Issue by ThomasLuypaert** [teunbrand/ggh4x#113] opened 2023-05-25 16:46 UTC
Hi Teun, 

First of all, thanks a lot for making this package, you've saved me a lot of time and trouble trying to plot rasters in the polar coordinate system. I'm using your function to map daily patterns in the occurrence of sound over a certain period. I'm getting very close to the plot I want to produce, with one final hurdle: there are always grey lines in between my pixels. 

I've encountered this issue before in ggplot with geom_tile, where this can be resolved by setting both the color and fill options. However, this does not seem to help using geom_polygonraster. 

Here is an example of a plot I'm getting: 

![cover_chapter_1](https://github.com/teunbrand/ggh4x/assets/52928299/f6f63e84-e135-4b4a-bbaf-bf052ae91882)

As you can see, there are faint grey lines between my pixels, which creates a weird star-shaped pattern in some areas of the plot. 

Here is the code I'm using to produce this plot:

```
polar_plot <- 
  
  ggplot(Fuzaca_df_long, aes(x = variable, y = as.numeric(frequency), color = value, fill = value))+
  
  ggh4x::geom_polygonraster()+
  
  scale_color_viridis_c(option = "A", end = 1, na.value = "black")+
  
  scale_fill_viridis_c(option = "A", end = 1, na.value = "black")+
  
  scale_x_discrete(expand = c(0,0))+
  scale_y_discrete(expand = c(0,0))+

  coord_polar()+

  theme(
    axis.line = element_blank(), 
    axis.text = element_blank(), 
    axis.title = element_blank(), 
    axis.ticks = element_blank(), 
    plot.background = element_rect(color = "black", fill = "black"), 
    panel.background = element_rect(color = "black", fill = "black"), 
    plot.margin = element_blank()
  ) 
```

If you have any suggestions on how this behaviour may be avoided, that would help me out a great deal!

Cheers, 
Thomas

**Comment by teunbrand** [comment] 2023-05-25 22:38
Hi Thomas,

Thanks for filing this issue. Unfortunately, there isn't a lot that I can do as the underlying problem originates in the graphics device. In particular, the anti-aliasing setting, that for most but not all devices anti-aliases lines but not fills, causes the Moiré patterning you see as stars in your plot. I wish I had a better solution, but if you can control this with geom_tile(), wouldn't that just work better?

**Comment by teunbrand** [comment] 2023-05-26 09:49
Well you might be interested to try the dev version of ggplot2 for this because drawing rectangles in polar coordinates have been sped up considerably for many rectangles (see https://github.com/tidyverse/ggplot2/pull/5081). I can take a look at the gap issue, but don't know how to reproduce it, so if you have some dummy data + code that makes this gap it would be easier to test solutions.

**Comment by teunbrand** [comment] 2023-07-15 07:22
I'm going to close this issue as I think that the underlying issue is with how graphics devices work, which I don't have a lot of control over from gg4hx's POV.

**Closed by teunbrand** 2023-07-15 07:22 UTC
