### ISSUE TITLE
Persisting error in facet_nested

### ISSUE THREAD

**Issue by ayeletperes** [teunbrand/ggh4x#49] opened 2021-08-25 08:47 UTC
Hey,

I've tried using the function facet_nested but I get this error: "Error: widths must be a unit object"

I thought it might be my code, but it also happens with the example code in the README.

Session info:

![image](https://user-images.githubusercontent.com/26592225/130758991-c4ca3e36-e3fb-4d82-b4a4-0c2aa4366b5f.png)

Thanks

**Comment by teunbrand** [comment] 2021-08-25 09:33
Hi there,

Yes I can reproduce this bug on R3.6.3 and I think it is due to pre-R4.0 unit operations being more fragile than >R4.0.

For example, on R3.6.3:
``` r
(x <- grid::unit(c(1, 2), "npc"))
#> [1] 1npc 2npc

x[[1]]
#> [1] 1
```
Whereas on R4.0.5:
``` r
(x <- grid::unit(c(1, 2), "npc"))
#> [1] 1npc 2npc

x[[1]]
#> [1] 1npc
```
Perhaps I should set the R versions requirement to >4.0.0 in the description file. I'll leave this open in case other people also experience this bug. I think the previous version didn't have this bug in R3.6, so if you specifically want to use facet_nested, you could install that version.

**Comment by mimi3421** [comment] 2021-09-08 11:29
I think this situation may be due to the little difference / bug R treating `rep(x, length.out=y)` and `rep_len(x, length.out=y)` in different version. 
In R 3.6, `rep(unit(1,"npc"),length.out=2)` returns `[1] 1npc 1npc` while `rep_len(unit(1,"npc"),length.out=2)` returns `[1] 1 1`

**Comment by teunbrand** [comment] 2021-09-08 12:03
I can replace `rep_len(x, y)` with `rep(x, length.out = y)` without breaking any unit tests on R4.0, if that helps for people working in R 3.6. The unit tests on R3.6 will remain broken\* due to the update to grid units, so I can't really promise everything is fixed, but it seems possible to use nested facets again. Let me know if that sounds agreeable to you.

\* Checking for correctness of `grid::unit()` output is different between the two versions and I'm not keen on refactoring unit tests with branches for different R versions.

**Comment by mimi3421** [comment] 2021-09-08 12:49
Thanks for maintaining this excellent package. 

I also consider it would be a hard work to maintain two versions at the same time as great changes has been made between the two version of R. 

I have uploaded an simply fixed version ![here](https://github.com/mimi3421/ggh4x/releases/tag/v0.2.0_fixed_for_R3.6) if anyone wants to have a test.

**Comment by teunbrand** [comment] 2021-09-08 13:24
Thanks mimi3421 for having uploaded a tarball with a fixed version.
For future cases, feel free to open a pull request with suggested changes. It's a bit more transparent to people what code has been changed and github will show that you've contributed.

Meanwhile, I also have commited some changes that I think might fix this problem for R3.6.
These can be installed with:
``` r
remotes::install_github("teunbrand/ggh4x@4e242295da442e0e412c7c3e713a383f603ceda0")
```

**Comment by llrs** [comment] 2021-09-20 09:40
Many thanks for providing this hot fix (and the package!). I can confirm 4e242295da442e0e412c7c3e713a383f603ceda0 works for me on R 3.6.3.

**Comment by teunbrand** [comment] 2021-11-24 14:52
The fix is soon propagated to CRAN, so I'll close this.

**Closed by teunbrand** 2021-11-24 14:52 UTC
Labels: bug
